spring.application.name=msCaja

server.port=8091

spring.datasource.url=jdbc:mysql://localhost:3306/caja_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
